author = Artur Tarassow
email = atecon@posteo.de
version = 0.3
date = 2020-01-01
description = Encoder based on categorical variables
tags = C10
min-version = 2018a
data-requirement = no-data-ok
public = ohe_encode binary_encode median_encode means_encode pca_encode low_rank_encode mnl_encode
help = CategoryEncoders_help.txt
sample-script = CategoryEncoders_sample.inp
