author = Artur Tarassow
email = atecon@posteo.de
version = 0.4
date = 2021-04-03
description = Encoder based on categorical variables
tags = C10
min-version = 2020b
public = ohe_encode binary_encode median_encode means_encode pca_encode low_rank_encode mnl_encode stats_by_group impose_by_group
help = CategoryEncoders_help.txt
sample-script = CategoryEncoders_sample.inp
